spring.application.name=SmartShop

# Datasource Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/smartshop_db
spring.datasource.username=smartshop_user
spring.datasource.password=smartshop_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Jackson
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

# Business Configuration
smartshop.tva.rate=0.20

